name: Deployment to apitest.elma.online

on:
  push:
    branches:
      - dev

jobs:
  build:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    name: ssh into server, pull from repo, build test release and restart pm2
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.SSH_PATH }}
          git pull
          yarn
          yarn build-release
          rm -r ${{ secrets.SSH_PATH }}/deploy/*
          cp -R ${{ secrets.SSH_PATH }}/build/* ${{ secrets.SSH_PATH }}/deploy/
