name: Deployment to api.elma.online

on:
  push:
    branches:
      - master

jobs:
  build:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    name: ssh into server, pull from repo, build release and and copy to pm2 watched path
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo chown ${{ secrets.SSH_USERNAME }}:${{ secrets.SSH_USERNAME }} ${{ secrets.SSH_PATH }}/.git/index
          cd ${{ secrets.SSH_PATH_LIVE }}
          git pull
          yarn
          yarn build-release
          rm -r ${{ secrets.SSH_PATH_LIVE }}/deploy/*
          cp -R ${{ secrets.SSH_PATH_LIVE }}/build/* ${{ secrets.SSH_PATH_LIVE }}/deploy/
