name: Deployment to apitest.elma.online

on:
  push:
    branches:
      - dev

jobs:
  build:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    name: ssh into server, pull from repo, build test release and and copy to pm2 watched path
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ${{ secrets.SSH_PATH }}
          git pull
          yarn
          pm2 restart api
